export const GET_ERRORS = "GET_ERRORS";

export const GET_BEHAVIOR_VERSIONS = "GET_BEHAVIOR_VERSIONS";
export const GET_BEHAVIOR_VERSION = "GET_BEHAVIOR_VERSION";
export const DELETE_BEHAVIOR_VERSION = "DELETE_BEHAVIOR_VERSION";

export const GET_BRAND_NAMES = "GET_BRAND_NAMES";
export const GET_BRAND_NAME = "GET_BRAND_NAME";
export const DELETE_BRAND_NAME = "DELETE_BRAND_NAME";